export const JOB = [
    {
        photo: "/public/jobIcon/Logo (1).png",
        time: "10 Minutes Ago",
        title: "Software Engineer",
        company: "ABC Corp",
        location: "New York",
        type: "full-time",
        salary: "80,000$",
        category: "Hotels & Tourism",
    },
    {
        photo: "/jobIcon/Logo (2).png",
        time: "1 Hour Ago",
        title: "Software Engineer",
        company: "ABC Corp",
        location: "New York",
        type: "full-time",
        salary: "80,000$",
        category: "Hotels & Tourism",
    },
    {
        photo: "/jobIcon/Logo (3).png",
        time: "20 Minutes Ago",
        title: "Software Engineer",
        company: "ABC Corp",
        location: "New York",
        type: "full-time",
        salary: "80,000$",
        category: "Hotels & Tourism",
    },
    {
        photo: "/jobIcon/Logo (4).png",
        time: "50 Minutes Ago",
        title: "Software Engineer",
        company: "ABC Corp",
        location: "Cairo",
        type: "full-time",
        salary: "8,000EGP",
        category: "Coding",
    },
    {
        photo: "/jobIcon/Logo (5).png",
        time: "30 Minutes Ago",
        title: "Software Engineer",
        company: "ABC Corp",
        location: "Cairo",
        type: "full-time",
        salary: "5,000EGP",
        category: "Coding",
    },
    {
        photo: "/jobIcon/Logo (6).png",
        time: "50 Minutes Ago",
        title: "Software Engineer",
        company: "ABC Corp",
        location: "Cairo",
        type: "full-time",
        salary: "8,000EGP",
        category: "Coding",
    }
];
